
// -*- C++ -*-
// $Id: Version.h 2964 2018-01-19 17:34:44Z taoadmin $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 2
#define ACE_BETA_VERSION 0
#define ACE_VERSION "6.2a_p14"
#define ACE_OCI_PATCHLEVEL 14
#define ACE_OCI_REV a
