// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_MESSAGINGS_XTY8WX_H_
#define _TAO_IDL_MESSAGINGS_XTY8WX_H_

#include /**/ "ace/pre.h"

#include "tao/Messaging/Messaging.h"
#include "tao/Messaging/Messaging_SyncScope_PolicyS.h"
#include "tao/Messaging/Messaging_RT_PolicyS.h"
#include "tao/Messaging/Messaging_No_ImplS.h"
#include "tao/Messaging/TAO_ExtS.h"
#include "tao/Messaging/PollableS.h"
#include "tao/Messaging/ExceptionHolderS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/TypeCode_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_MESSAGING_REPLYHANDLER__SARG_TRAITS_)
#define _MESSAGING_REPLYHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Messaging::ReplyHandler>
    : public
        Object_SArg_Traits_T<
            ::Messaging::ReplyHandler_ptr,
            ::Messaging::ReplyHandler_var,
            ::Messaging::ReplyHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_Messaging
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:76

  class ReplyHandler;
  typedef ReplyHandler *ReplyHandler_ptr;

  class _TAO_ReplyHandler_Direct_Proxy_Impl;

  class TAO_Messaging_Export ReplyHandler
    : public virtual PortableServer::ServantBase
  {
  protected:
    ReplyHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::Messaging::ReplyHandler _stub_type;
    typedef ::Messaging::ReplyHandler_ptr _stub_ptr_type;
    typedef ::Messaging::ReplyHandler_var _stub_var_type;

    ReplyHandler (const ReplyHandler& rhs);
    virtual ~ReplyHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::Messaging::ReplyHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_interface/direct_proxy_impl_sh.cpp:27

  ///////////////////////////////////////////////////////////////////////
  //                    Direct  Impl. Declaration
  //

  class TAO_Messaging_Export _TAO_ReplyHandler_Direct_Proxy_Impl
  {
  public:
    virtual ~_TAO_ReplyHandler_Direct_Proxy_Impl (void);
  };

  //
  //                Direct  Proxy Impl. Declaration
  ///////////////////////////////////////////////////////////////////////

  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module Messaging

TAO_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

