// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_CRYPTOBUILTINS_EMTCUE_H_
#define _TAO_IDL_CRYPTOBUILTINS_EMTCUE_H_

#include /**/ "ace/pre.h"

#include "CryptoBuiltInC.h"
#include "dds/DdsDcpsCoreS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Fixed_Array_SArgument_T.h"
#include "tao/PortableServer/Var_Array_SArgument_T.h"

// Skeleton file generation suppressed with command line option -SS

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoTransformKind_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::CryptoTransformKind_var,
            ::OpenDDS::Security::CryptoTransformKind_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoTransformKeyId_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::CryptoTransformKeyId_var,
            ::OpenDDS::Security::CryptoTransformKeyId_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoTransformIdentifier>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Security::CryptoTransformIdentifier,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::Security::KeyOctetSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::KeyOctetSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::KeyMaterial_AES_GCM_GMAC>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::KeyMaterial_AES_GCM_GMAC,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::Security::KeyMaterial_AES_GCM_GMAC_Seq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::KeyMaterial_AES_GCM_GMAC_Seq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::Security::SessionIdType_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::SessionIdType_var,
            ::OpenDDS::Security::SessionIdType_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::Security::IV_SuffixType_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::IV_SuffixType_var,
            ::OpenDDS::Security::IV_SuffixType_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoHeader>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Security::CryptoHeader,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoContent>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::CryptoContent,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::Security::ReceiverMAC_Type_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::ReceiverMAC_Type_var,
            ::OpenDDS::Security::ReceiverMAC_Type_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::ReceiverSpecificMAC>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::Security::ReceiverSpecificMAC,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::Security::ReceiverSpecificMACSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::ReceiverSpecificMACSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::Security::CommonMAC_Type_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::Security::CommonMAC_Type_var,
            ::OpenDDS::Security::CommonMAC_Type_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::Security::CryptoFooter>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::Security::CryptoFooter,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




OPENDDS_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

