// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDSDCPSTYPESUPPORTEXTC_9AXYHK_H_
#define _TAO_IDL_DDSDCPSTYPESUPPORTEXTC_9AXYHK_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "dds/DCPS/dcps_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OpenDDS_Dcps_Export

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace OpenDDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:38

  namespace DCPS
  {

    // TAO_IDL - Generated from
    // be/be_interface.cpp:751

#if !defined (_OPENDDS_DCPS_TYPESUPPORT__VAR_OUT_CH_)
#define _OPENDDS_DCPS_TYPESUPPORT__VAR_OUT_CH_

    class TypeSupport;
    typedef TypeSupport *TypeSupport_ptr;

    typedef
      TAO_Objref_Var_T<
          TypeSupport
        >
      TypeSupport_var;
    
    typedef
      TAO_Objref_Out_T<
          TypeSupport
        >
      TypeSupport_out;

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:43

    class OpenDDS_Dcps_Export TypeSupport
      : public virtual ::DDS::TypeSupport
    
    {
    public:

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      typedef TypeSupport_ptr _ptr_type;
      typedef TypeSupport_var _var_type;
      typedef TypeSupport_out _out_type;

      // The static operations.
      static TypeSupport_ptr _duplicate (TypeSupport_ptr obj);

      static void _tao_release (TypeSupport_ptr obj);

      static TypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
      static TypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
      static TypeSupport_ptr _nil (void);

      virtual ::DDS::DataWriter_ptr create_datawriter (
        void) = 0;

      virtual ::DDS::DataReader_ptr create_datareader (
        void) = 0;

      virtual ::DDS::DataReader_ptr create_multitopic_datareader (
        void) = 0;

      virtual ::CORBA::Boolean has_dcps_key (
        void) = 0;

      virtual ::DDS::ReturnCode_t unregister_type (
        ::DDS::DomainParticipant_ptr domain,
        const char * type_name) = 0;

      // TAO_IDL - Generated from
      // be/be_visitor_interface/interface_ch.cpp:140

      virtual ::CORBA::Boolean _is_a (const char *type_id);
      virtual const char* _interface_repository_id (void) const;
      virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
    
    protected:
      // Abstract or local interface only.
      TypeSupport (void);

      

      virtual ~TypeSupport (void);
    
    private:
      // Private and unimplemented for concrete interfaces.
      TypeSupport (const TypeSupport &);

      void operator= (const TypeSupport &);
    };
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:67
  
  } // module OpenDDS::DCPS

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module OpenDDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_OPENDDS_DCPS_TYPESUPPORT__TRAITS_)
#define _OPENDDS_DCPS_TYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::OpenDDS::DCPS::TypeSupport>
  {
    static ::OpenDDS::DCPS::TypeSupport_ptr duplicate (
        ::OpenDDS::DCPS::TypeSupport_ptr p);
    static void release (
        ::OpenDDS::DCPS::TypeSupport_ptr p);
    static ::OpenDDS::DCPS::TypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::OpenDDS::DCPS::TypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_codegen.cpp:1703


OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "DdsDcpsTypeSupportExtC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

