// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_DDSDCPSINFOUTILSS_5MOVJA_H_
#define _TAO_IDL_DDSDCPSINFOUTILSS_5MOVJA_H_

#include /**/ "ace/pre.h"

#include "DdsDcpsInfoUtilsC.h"
#include "dds/DdsDcpsCoreS.h"
#include "dds/DdsDcpsGuidS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/BD_String_SArgument_T.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Fixed_Array_SArgument_T.h"
#include "tao/PortableServer/Var_Array_SArgument_T.h"

// Skeleton file generation suppressed with command line option -SS

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::TransportLocator>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::TransportLocator,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::TransportLocatorSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::TransportLocatorSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::IncompatibleQosStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::IncompatibleQosStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::AddDomainStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::AddDomainStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:904

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::TopicStatus>
    : public
        Basic_SArg_Traits_T<
            ::OpenDDS::DCPS::TopicStatus,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::WriterAssociation>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::WriterAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::ReaderAssociation>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::ReaderAssociation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::WriterIdSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::WriterIdSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::ReaderIdSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::ReaderIdSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::OctetArray16_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::DCPS::OctetArray16_var,
            ::OpenDDS::DCPS::OctetArray16_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::Locator_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::Locator_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::LocatorSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::LocatorSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_STRING256256__SARG_TRAITS_)
#define _STRING256256__SARG_TRAITS_

  template<>
  class SArg_Traits<String256_256>
    : public
        BD_String_SArg_Traits_T<
            CORBA::String_var,
            256,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::ContentFilterProperty_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::ContentFilterProperty_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::ReaderProxy_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::ReaderProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::DiscoveredReaderData>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::DiscoveredReaderData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::WriterProxy_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::WriterProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::DCPS::DiscoveredWriterData>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::DCPS::DiscoveredWriterData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




OPENDDS_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

