// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDSDCPSCORETYPESUPPORTC_OSGU5M_H_
#define _TAO_IDL_DDSDCPSCORETYPESUPPORTC_OSGU5M_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "dds/DCPS/dcps_export.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "DdsDcpsCoreC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OpenDDS_Dcps_Export

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDS::ParticipantBuiltinTopicData, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> ParticipantBuiltinTopicDataSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_)
#define _DDS_PARTICIPANTBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_

  class ParticipantBuiltinTopicDataTypeSupport;
  typedef ParticipantBuiltinTopicDataTypeSupport *ParticipantBuiltinTopicDataTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        ParticipantBuiltinTopicDataTypeSupport
      >
    ParticipantBuiltinTopicDataTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        ParticipantBuiltinTopicDataTypeSupport
      >
    ParticipantBuiltinTopicDataTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export ParticipantBuiltinTopicDataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef ParticipantBuiltinTopicDataTypeSupport_ptr _ptr_type;
    typedef ParticipantBuiltinTopicDataTypeSupport_var _var_type;
    typedef ParticipantBuiltinTopicDataTypeSupport_out _out_type;

    // The static operations.
    static ParticipantBuiltinTopicDataTypeSupport_ptr _duplicate (ParticipantBuiltinTopicDataTypeSupport_ptr obj);

    static void _tao_release (ParticipantBuiltinTopicDataTypeSupport_ptr obj);

    static ParticipantBuiltinTopicDataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ParticipantBuiltinTopicDataTypeSupport (void);

    

    virtual ~ParticipantBuiltinTopicDataTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ParticipantBuiltinTopicDataTypeSupport (const ParticipantBuiltinTopicDataTypeSupport &);

    void operator= (const ParticipantBuiltinTopicDataTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_)
#define _DDS_PARTICIPANTBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_

  class ParticipantBuiltinTopicDataDataWriter;
  typedef ParticipantBuiltinTopicDataDataWriter *ParticipantBuiltinTopicDataDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        ParticipantBuiltinTopicDataDataWriter
      >
    ParticipantBuiltinTopicDataDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        ParticipantBuiltinTopicDataDataWriter
      >
    ParticipantBuiltinTopicDataDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export ParticipantBuiltinTopicDataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef ParticipantBuiltinTopicDataDataWriter_ptr _ptr_type;
    typedef ParticipantBuiltinTopicDataDataWriter_var _var_type;
    typedef ParticipantBuiltinTopicDataDataWriter_out _out_type;

    // The static operations.
    static ParticipantBuiltinTopicDataDataWriter_ptr _duplicate (ParticipantBuiltinTopicDataDataWriter_ptr obj);

    static void _tao_release (ParticipantBuiltinTopicDataDataWriter_ptr obj);

    static ParticipantBuiltinTopicDataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDS::ParticipantBuiltinTopicData & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDS::ParticipantBuiltinTopicData & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDS::ParticipantBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDS::ParticipantBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDS::ParticipantBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDS::ParticipantBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDS::ParticipantBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDS::ParticipantBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::ParticipantBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::ParticipantBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ParticipantBuiltinTopicDataDataWriter (void);

    

    virtual ~ParticipantBuiltinTopicDataDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ParticipantBuiltinTopicDataDataWriter (const ParticipantBuiltinTopicDataDataWriter &);

    void operator= (const ParticipantBuiltinTopicDataDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATADATAREADER__VAR_OUT_CH_)
#define _DDS_PARTICIPANTBUILTINTOPICDATADATAREADER__VAR_OUT_CH_

  class ParticipantBuiltinTopicDataDataReader;
  typedef ParticipantBuiltinTopicDataDataReader *ParticipantBuiltinTopicDataDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        ParticipantBuiltinTopicDataDataReader
      >
    ParticipantBuiltinTopicDataDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        ParticipantBuiltinTopicDataDataReader
      >
    ParticipantBuiltinTopicDataDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export ParticipantBuiltinTopicDataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef ParticipantBuiltinTopicDataDataReader_ptr _ptr_type;
    typedef ParticipantBuiltinTopicDataDataReader_var _var_type;
    typedef ParticipantBuiltinTopicDataDataReader_out _out_type;

    // The static operations.
    static ParticipantBuiltinTopicDataDataReader_ptr _duplicate (ParticipantBuiltinTopicDataDataReader_ptr obj);

    static void _tao_release (ParticipantBuiltinTopicDataDataReader_ptr obj);

    static ParticipantBuiltinTopicDataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ParticipantBuiltinTopicDataDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDS::ParticipantBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDS::ParticipantBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDS::ParticipantBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDS::ParticipantBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::ParticipantBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::ParticipantBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ParticipantBuiltinTopicDataDataReader (void);

    

    virtual ~ParticipantBuiltinTopicDataDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ParticipantBuiltinTopicDataDataReader (const ParticipantBuiltinTopicDataDataReader &);

    void operator= (const ParticipantBuiltinTopicDataDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDS::PublicationBuiltinTopicData, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> PublicationBuiltinTopicDataSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_)
#define _DDS_PUBLICATIONBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_

  class PublicationBuiltinTopicDataTypeSupport;
  typedef PublicationBuiltinTopicDataTypeSupport *PublicationBuiltinTopicDataTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        PublicationBuiltinTopicDataTypeSupport
      >
    PublicationBuiltinTopicDataTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        PublicationBuiltinTopicDataTypeSupport
      >
    PublicationBuiltinTopicDataTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export PublicationBuiltinTopicDataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef PublicationBuiltinTopicDataTypeSupport_ptr _ptr_type;
    typedef PublicationBuiltinTopicDataTypeSupport_var _var_type;
    typedef PublicationBuiltinTopicDataTypeSupport_out _out_type;

    // The static operations.
    static PublicationBuiltinTopicDataTypeSupport_ptr _duplicate (PublicationBuiltinTopicDataTypeSupport_ptr obj);

    static void _tao_release (PublicationBuiltinTopicDataTypeSupport_ptr obj);

    static PublicationBuiltinTopicDataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PublicationBuiltinTopicDataTypeSupport (void);

    

    virtual ~PublicationBuiltinTopicDataTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    PublicationBuiltinTopicDataTypeSupport (const PublicationBuiltinTopicDataTypeSupport &);

    void operator= (const PublicationBuiltinTopicDataTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_)
#define _DDS_PUBLICATIONBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_

  class PublicationBuiltinTopicDataDataWriter;
  typedef PublicationBuiltinTopicDataDataWriter *PublicationBuiltinTopicDataDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        PublicationBuiltinTopicDataDataWriter
      >
    PublicationBuiltinTopicDataDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        PublicationBuiltinTopicDataDataWriter
      >
    PublicationBuiltinTopicDataDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export PublicationBuiltinTopicDataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef PublicationBuiltinTopicDataDataWriter_ptr _ptr_type;
    typedef PublicationBuiltinTopicDataDataWriter_var _var_type;
    typedef PublicationBuiltinTopicDataDataWriter_out _out_type;

    // The static operations.
    static PublicationBuiltinTopicDataDataWriter_ptr _duplicate (PublicationBuiltinTopicDataDataWriter_ptr obj);

    static void _tao_release (PublicationBuiltinTopicDataDataWriter_ptr obj);

    static PublicationBuiltinTopicDataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDS::PublicationBuiltinTopicData & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDS::PublicationBuiltinTopicData & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDS::PublicationBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDS::PublicationBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDS::PublicationBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDS::PublicationBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDS::PublicationBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDS::PublicationBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::PublicationBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::PublicationBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PublicationBuiltinTopicDataDataWriter (void);

    

    virtual ~PublicationBuiltinTopicDataDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    PublicationBuiltinTopicDataDataWriter (const PublicationBuiltinTopicDataDataWriter &);

    void operator= (const PublicationBuiltinTopicDataDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATADATAREADER__VAR_OUT_CH_)
#define _DDS_PUBLICATIONBUILTINTOPICDATADATAREADER__VAR_OUT_CH_

  class PublicationBuiltinTopicDataDataReader;
  typedef PublicationBuiltinTopicDataDataReader *PublicationBuiltinTopicDataDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        PublicationBuiltinTopicDataDataReader
      >
    PublicationBuiltinTopicDataDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        PublicationBuiltinTopicDataDataReader
      >
    PublicationBuiltinTopicDataDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export PublicationBuiltinTopicDataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef PublicationBuiltinTopicDataDataReader_ptr _ptr_type;
    typedef PublicationBuiltinTopicDataDataReader_var _var_type;
    typedef PublicationBuiltinTopicDataDataReader_out _out_type;

    // The static operations.
    static PublicationBuiltinTopicDataDataReader_ptr _duplicate (PublicationBuiltinTopicDataDataReader_ptr obj);

    static void _tao_release (PublicationBuiltinTopicDataDataReader_ptr obj);

    static PublicationBuiltinTopicDataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PublicationBuiltinTopicDataDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDS::PublicationBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDS::PublicationBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDS::PublicationBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDS::PublicationBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::PublicationBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::PublicationBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PublicationBuiltinTopicDataDataReader (void);

    

    virtual ~PublicationBuiltinTopicDataDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    PublicationBuiltinTopicDataDataReader (const PublicationBuiltinTopicDataDataReader &);

    void operator= (const PublicationBuiltinTopicDataDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDS::SubscriptionBuiltinTopicData, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> SubscriptionBuiltinTopicDataSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_

  class SubscriptionBuiltinTopicDataTypeSupport;
  typedef SubscriptionBuiltinTopicDataTypeSupport *SubscriptionBuiltinTopicDataTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        SubscriptionBuiltinTopicDataTypeSupport
      >
    SubscriptionBuiltinTopicDataTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        SubscriptionBuiltinTopicDataTypeSupport
      >
    SubscriptionBuiltinTopicDataTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export SubscriptionBuiltinTopicDataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SubscriptionBuiltinTopicDataTypeSupport_ptr _ptr_type;
    typedef SubscriptionBuiltinTopicDataTypeSupport_var _var_type;
    typedef SubscriptionBuiltinTopicDataTypeSupport_out _out_type;

    // The static operations.
    static SubscriptionBuiltinTopicDataTypeSupport_ptr _duplicate (SubscriptionBuiltinTopicDataTypeSupport_ptr obj);

    static void _tao_release (SubscriptionBuiltinTopicDataTypeSupport_ptr obj);

    static SubscriptionBuiltinTopicDataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SubscriptionBuiltinTopicDataTypeSupport (void);

    

    virtual ~SubscriptionBuiltinTopicDataTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SubscriptionBuiltinTopicDataTypeSupport (const SubscriptionBuiltinTopicDataTypeSupport &);

    void operator= (const SubscriptionBuiltinTopicDataTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_

  class SubscriptionBuiltinTopicDataDataWriter;
  typedef SubscriptionBuiltinTopicDataDataWriter *SubscriptionBuiltinTopicDataDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        SubscriptionBuiltinTopicDataDataWriter
      >
    SubscriptionBuiltinTopicDataDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        SubscriptionBuiltinTopicDataDataWriter
      >
    SubscriptionBuiltinTopicDataDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export SubscriptionBuiltinTopicDataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SubscriptionBuiltinTopicDataDataWriter_ptr _ptr_type;
    typedef SubscriptionBuiltinTopicDataDataWriter_var _var_type;
    typedef SubscriptionBuiltinTopicDataDataWriter_out _out_type;

    // The static operations.
    static SubscriptionBuiltinTopicDataDataWriter_ptr _duplicate (SubscriptionBuiltinTopicDataDataWriter_ptr obj);

    static void _tao_release (SubscriptionBuiltinTopicDataDataWriter_ptr obj);

    static SubscriptionBuiltinTopicDataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDS::SubscriptionBuiltinTopicData & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDS::SubscriptionBuiltinTopicData & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDS::SubscriptionBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDS::SubscriptionBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::SubscriptionBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SubscriptionBuiltinTopicDataDataWriter (void);

    

    virtual ~SubscriptionBuiltinTopicDataDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SubscriptionBuiltinTopicDataDataWriter (const SubscriptionBuiltinTopicDataDataWriter &);

    void operator= (const SubscriptionBuiltinTopicDataDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATADATAREADER__VAR_OUT_CH_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATADATAREADER__VAR_OUT_CH_

  class SubscriptionBuiltinTopicDataDataReader;
  typedef SubscriptionBuiltinTopicDataDataReader *SubscriptionBuiltinTopicDataDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        SubscriptionBuiltinTopicDataDataReader
      >
    SubscriptionBuiltinTopicDataDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        SubscriptionBuiltinTopicDataDataReader
      >
    SubscriptionBuiltinTopicDataDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export SubscriptionBuiltinTopicDataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SubscriptionBuiltinTopicDataDataReader_ptr _ptr_type;
    typedef SubscriptionBuiltinTopicDataDataReader_var _var_type;
    typedef SubscriptionBuiltinTopicDataDataReader_out _out_type;

    // The static operations.
    static SubscriptionBuiltinTopicDataDataReader_ptr _duplicate (SubscriptionBuiltinTopicDataDataReader_ptr obj);

    static void _tao_release (SubscriptionBuiltinTopicDataDataReader_ptr obj);

    static SubscriptionBuiltinTopicDataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SubscriptionBuiltinTopicDataDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDS::SubscriptionBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDS::SubscriptionBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDS::SubscriptionBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDS::SubscriptionBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::SubscriptionBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::SubscriptionBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SubscriptionBuiltinTopicDataDataReader (void);

    

    virtual ~SubscriptionBuiltinTopicDataDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SubscriptionBuiltinTopicDataDataReader (const SubscriptionBuiltinTopicDataDataReader &);

    void operator= (const SubscriptionBuiltinTopicDataDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDS::TopicBuiltinTopicData, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> TopicBuiltinTopicDataSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_TOPICBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_)
#define _DDS_TOPICBUILTINTOPICDATATYPESUPPORT__VAR_OUT_CH_

  class TopicBuiltinTopicDataTypeSupport;
  typedef TopicBuiltinTopicDataTypeSupport *TopicBuiltinTopicDataTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        TopicBuiltinTopicDataTypeSupport
      >
    TopicBuiltinTopicDataTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        TopicBuiltinTopicDataTypeSupport
      >
    TopicBuiltinTopicDataTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export TopicBuiltinTopicDataTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TopicBuiltinTopicDataTypeSupport_ptr _ptr_type;
    typedef TopicBuiltinTopicDataTypeSupport_var _var_type;
    typedef TopicBuiltinTopicDataTypeSupport_out _out_type;

    // The static operations.
    static TopicBuiltinTopicDataTypeSupport_ptr _duplicate (TopicBuiltinTopicDataTypeSupport_ptr obj);

    static void _tao_release (TopicBuiltinTopicDataTypeSupport_ptr obj);

    static TopicBuiltinTopicDataTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TopicBuiltinTopicDataTypeSupport (void);

    

    virtual ~TopicBuiltinTopicDataTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TopicBuiltinTopicDataTypeSupport (const TopicBuiltinTopicDataTypeSupport &);

    void operator= (const TopicBuiltinTopicDataTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_TOPICBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_)
#define _DDS_TOPICBUILTINTOPICDATADATAWRITER__VAR_OUT_CH_

  class TopicBuiltinTopicDataDataWriter;
  typedef TopicBuiltinTopicDataDataWriter *TopicBuiltinTopicDataDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        TopicBuiltinTopicDataDataWriter
      >
    TopicBuiltinTopicDataDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        TopicBuiltinTopicDataDataWriter
      >
    TopicBuiltinTopicDataDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export TopicBuiltinTopicDataDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TopicBuiltinTopicDataDataWriter_ptr _ptr_type;
    typedef TopicBuiltinTopicDataDataWriter_var _var_type;
    typedef TopicBuiltinTopicDataDataWriter_out _out_type;

    // The static operations.
    static TopicBuiltinTopicDataDataWriter_ptr _duplicate (TopicBuiltinTopicDataDataWriter_ptr obj);

    static void _tao_release (TopicBuiltinTopicDataDataWriter_ptr obj);

    static TopicBuiltinTopicDataDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDS::TopicBuiltinTopicData & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDS::TopicBuiltinTopicData & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDS::TopicBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDS::TopicBuiltinTopicData & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDS::TopicBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDS::TopicBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDS::TopicBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDS::TopicBuiltinTopicData & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::TopicBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::TopicBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TopicBuiltinTopicDataDataWriter (void);

    

    virtual ~TopicBuiltinTopicDataDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TopicBuiltinTopicDataDataWriter (const TopicBuiltinTopicDataDataWriter &);

    void operator= (const TopicBuiltinTopicDataDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDS_TOPICBUILTINTOPICDATADATAREADER__VAR_OUT_CH_)
#define _DDS_TOPICBUILTINTOPICDATADATAREADER__VAR_OUT_CH_

  class TopicBuiltinTopicDataDataReader;
  typedef TopicBuiltinTopicDataDataReader *TopicBuiltinTopicDataDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        TopicBuiltinTopicDataDataReader
      >
    TopicBuiltinTopicDataDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        TopicBuiltinTopicDataDataReader
      >
    TopicBuiltinTopicDataDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class OpenDDS_Dcps_Export TopicBuiltinTopicDataDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef TopicBuiltinTopicDataDataReader_ptr _ptr_type;
    typedef TopicBuiltinTopicDataDataReader_var _var_type;
    typedef TopicBuiltinTopicDataDataReader_out _out_type;

    // The static operations.
    static TopicBuiltinTopicDataDataReader_ptr _duplicate (TopicBuiltinTopicDataDataReader_ptr obj);

    static void _tao_release (TopicBuiltinTopicDataDataReader_ptr obj);

    static TopicBuiltinTopicDataDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TopicBuiltinTopicDataDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDS::TopicBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDS::TopicBuiltinTopicData & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDS::TopicBuiltinTopicDataSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDS::TopicBuiltinTopicDataSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDS::TopicBuiltinTopicData & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDS::TopicBuiltinTopicData & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TopicBuiltinTopicDataDataReader (void);

    

    virtual ~TopicBuiltinTopicDataDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    TopicBuiltinTopicDataDataReader (const TopicBuiltinTopicDataDataReader &);

    void operator= (const TopicBuiltinTopicDataDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATATYPESUPPORT__TRAITS_)
#define _DDS_PARTICIPANTBUILTINTOPICDATATYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::ParticipantBuiltinTopicDataTypeSupport>
  {
    static ::DDS::ParticipantBuiltinTopicDataTypeSupport_ptr duplicate (
        ::DDS::ParticipantBuiltinTopicDataTypeSupport_ptr p);
    static void release (
        ::DDS::ParticipantBuiltinTopicDataTypeSupport_ptr p);
    static ::DDS::ParticipantBuiltinTopicDataTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::ParticipantBuiltinTopicDataTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATADATAWRITER__TRAITS_)
#define _DDS_PARTICIPANTBUILTINTOPICDATADATAWRITER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::ParticipantBuiltinTopicDataDataWriter>
  {
    static ::DDS::ParticipantBuiltinTopicDataDataWriter_ptr duplicate (
        ::DDS::ParticipantBuiltinTopicDataDataWriter_ptr p);
    static void release (
        ::DDS::ParticipantBuiltinTopicDataDataWriter_ptr p);
    static ::DDS::ParticipantBuiltinTopicDataDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::ParticipantBuiltinTopicDataDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_PARTICIPANTBUILTINTOPICDATADATAREADER__TRAITS_)
#define _DDS_PARTICIPANTBUILTINTOPICDATADATAREADER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::ParticipantBuiltinTopicDataDataReader>
  {
    static ::DDS::ParticipantBuiltinTopicDataDataReader_ptr duplicate (
        ::DDS::ParticipantBuiltinTopicDataDataReader_ptr p);
    static void release (
        ::DDS::ParticipantBuiltinTopicDataDataReader_ptr p);
    static ::DDS::ParticipantBuiltinTopicDataDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::ParticipantBuiltinTopicDataDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATATYPESUPPORT__TRAITS_)
#define _DDS_PUBLICATIONBUILTINTOPICDATATYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::PublicationBuiltinTopicDataTypeSupport>
  {
    static ::DDS::PublicationBuiltinTopicDataTypeSupport_ptr duplicate (
        ::DDS::PublicationBuiltinTopicDataTypeSupport_ptr p);
    static void release (
        ::DDS::PublicationBuiltinTopicDataTypeSupport_ptr p);
    static ::DDS::PublicationBuiltinTopicDataTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::PublicationBuiltinTopicDataTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATADATAWRITER__TRAITS_)
#define _DDS_PUBLICATIONBUILTINTOPICDATADATAWRITER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::PublicationBuiltinTopicDataDataWriter>
  {
    static ::DDS::PublicationBuiltinTopicDataDataWriter_ptr duplicate (
        ::DDS::PublicationBuiltinTopicDataDataWriter_ptr p);
    static void release (
        ::DDS::PublicationBuiltinTopicDataDataWriter_ptr p);
    static ::DDS::PublicationBuiltinTopicDataDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::PublicationBuiltinTopicDataDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_PUBLICATIONBUILTINTOPICDATADATAREADER__TRAITS_)
#define _DDS_PUBLICATIONBUILTINTOPICDATADATAREADER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::PublicationBuiltinTopicDataDataReader>
  {
    static ::DDS::PublicationBuiltinTopicDataDataReader_ptr duplicate (
        ::DDS::PublicationBuiltinTopicDataDataReader_ptr p);
    static void release (
        ::DDS::PublicationBuiltinTopicDataDataReader_ptr p);
    static ::DDS::PublicationBuiltinTopicDataDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::PublicationBuiltinTopicDataDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATATYPESUPPORT__TRAITS_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATATYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::SubscriptionBuiltinTopicDataTypeSupport>
  {
    static ::DDS::SubscriptionBuiltinTopicDataTypeSupport_ptr duplicate (
        ::DDS::SubscriptionBuiltinTopicDataTypeSupport_ptr p);
    static void release (
        ::DDS::SubscriptionBuiltinTopicDataTypeSupport_ptr p);
    static ::DDS::SubscriptionBuiltinTopicDataTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::SubscriptionBuiltinTopicDataTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATADATAWRITER__TRAITS_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATADATAWRITER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::SubscriptionBuiltinTopicDataDataWriter>
  {
    static ::DDS::SubscriptionBuiltinTopicDataDataWriter_ptr duplicate (
        ::DDS::SubscriptionBuiltinTopicDataDataWriter_ptr p);
    static void release (
        ::DDS::SubscriptionBuiltinTopicDataDataWriter_ptr p);
    static ::DDS::SubscriptionBuiltinTopicDataDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::SubscriptionBuiltinTopicDataDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_SUBSCRIPTIONBUILTINTOPICDATADATAREADER__TRAITS_)
#define _DDS_SUBSCRIPTIONBUILTINTOPICDATADATAREADER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::SubscriptionBuiltinTopicDataDataReader>
  {
    static ::DDS::SubscriptionBuiltinTopicDataDataReader_ptr duplicate (
        ::DDS::SubscriptionBuiltinTopicDataDataReader_ptr p);
    static void release (
        ::DDS::SubscriptionBuiltinTopicDataDataReader_ptr p);
    static ::DDS::SubscriptionBuiltinTopicDataDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::SubscriptionBuiltinTopicDataDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_TOPICBUILTINTOPICDATATYPESUPPORT__TRAITS_)
#define _DDS_TOPICBUILTINTOPICDATATYPESUPPORT__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::TopicBuiltinTopicDataTypeSupport>
  {
    static ::DDS::TopicBuiltinTopicDataTypeSupport_ptr duplicate (
        ::DDS::TopicBuiltinTopicDataTypeSupport_ptr p);
    static void release (
        ::DDS::TopicBuiltinTopicDataTypeSupport_ptr p);
    static ::DDS::TopicBuiltinTopicDataTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::TopicBuiltinTopicDataTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_TOPICBUILTINTOPICDATADATAWRITER__TRAITS_)
#define _DDS_TOPICBUILTINTOPICDATADATAWRITER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::TopicBuiltinTopicDataDataWriter>
  {
    static ::DDS::TopicBuiltinTopicDataDataWriter_ptr duplicate (
        ::DDS::TopicBuiltinTopicDataDataWriter_ptr p);
    static void release (
        ::DDS::TopicBuiltinTopicDataDataWriter_ptr p);
    static ::DDS::TopicBuiltinTopicDataDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::TopicBuiltinTopicDataDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDS_TOPICBUILTINTOPICDATADATAREADER__TRAITS_)
#define _DDS_TOPICBUILTINTOPICDATADATAREADER__TRAITS_

  template<>
  struct OpenDDS_Dcps_Export Objref_Traits< ::DDS::TopicBuiltinTopicDataDataReader>
  {
    static ::DDS::TopicBuiltinTopicDataDataReader_ptr duplicate (
        ::DDS::TopicBuiltinTopicDataDataReader_ptr p);
    static void release (
        ::DDS::TopicBuiltinTopicDataDataReader_ptr p);
    static ::DDS::TopicBuiltinTopicDataDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDS::TopicBuiltinTopicDataDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_codegen.cpp:1703


OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "DdsDcpsCoreTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

