// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDSSECURITYPARAMSC_9WKAWY_H_
#define _TAO_IDL_DDSSECURITYPARAMSC_9WKAWY_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "dds/DCPS/dcps_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "DdsDcpsCoreC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OpenDDS_Dcps_Export

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:38

  namespace Security
  {

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::UShort ParameterId_t;
    typedef ::CORBA::UShort_out ParameterId_t_out;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_IDENTITY_TOKEN = 4097U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_PERMISSIONS_TOKEN = 4098U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_DATA_TAGS = 4099U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_ENDPOINT_SECURITY_INFO = 4100U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_PARTICIPANT_SECURITY_INFO = 4101U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::UShort PID_IDENTITY_STATUS_TOKEN = 4102U;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DataHolder;

    typedef
      ::TAO_Var_Var_T<
          DataHolder
        >
      DataHolder_var;

    typedef
      ::TAO_Out_T<
          DataHolder
        >
      DataHolder_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Dcps_Export DataHolder
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DataHolder_var _var_type;
      typedef DataHolder_out _out_type;
      
      ::TAO::String_Manager class_id;
      DDS::PropertySeq properties;
      DDS::BinaryPropertySeq binary_properties;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_DDS_SECURITY_DATAHOLDERSEQ_CH_)
#define _DDS_SECURITY_DATAHOLDERSEQ_CH_

    class DataHolderSeq;

    typedef
      ::TAO_VarSeq_Var_T<
          DataHolderSeq
        >
      DataHolderSeq_var;

    typedef
      ::TAO_Seq_Out_T<
          DataHolderSeq
        >
      DataHolderSeq_out;

    class OpenDDS_Dcps_Export DataHolderSeq
      : public
          ::TAO::unbounded_value_sequence<
              DataHolder
            >
    {
    public:
      DataHolderSeq (void);
      DataHolderSeq ( ::CORBA::ULong max);
      DataHolderSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        DataHolder* buffer,
        ::CORBA::Boolean release = false);
      DataHolderSeq (const DataHolderSeq &);
      virtual ~DataHolderSeq (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DataHolderSeq_var _var_type;
      typedef DataHolderSeq_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:513

    typedef DataHolder Token;
    typedef DataHolder_var Token_var;
    typedef DataHolder_out Token_out;

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:513

    typedef Token IdentityToken;
    typedef Token_var IdentityToken_var;
    typedef Token_out IdentityToken_out;

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:513

    typedef Token PermissionsToken;
    typedef Token_var PermissionsToken_var;
    typedef Token_out PermissionsToken_out;

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:513

    typedef Token IdentityStatusToken;
    typedef Token_var IdentityStatusToken_var;
    typedef Token_out IdentityStatusToken_out;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct Tag;

    typedef
      ::TAO_Var_Var_T<
          Tag
        >
      Tag_var;

    typedef
      ::TAO_Out_T<
          Tag
        >
      Tag_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Dcps_Export Tag
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef Tag_var _var_type;
      typedef Tag_out _out_type;
      
      ::TAO::String_Manager name;
      ::TAO::String_Manager value;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_DDS_SECURITY_TAGSEQ_CH_)
#define _DDS_SECURITY_TAGSEQ_CH_

    class TagSeq;

    typedef
      ::TAO_VarSeq_Var_T<
          TagSeq
        >
      TagSeq_var;

    typedef
      ::TAO_Seq_Out_T<
          TagSeq
        >
      TagSeq_out;

    class OpenDDS_Dcps_Export TagSeq
      : public
          ::TAO::unbounded_value_sequence<
              Tag
            >
    {
    public:
      TagSeq (void);
      TagSeq ( ::CORBA::ULong max);
      TagSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        Tag* buffer,
        ::CORBA::Boolean release = false);
      TagSeq (const TagSeq &);
      virtual ~TagSeq (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef TagSeq_var _var_type;
      typedef TagSeq_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DataTags;

    typedef
      ::TAO_Var_Var_T<
          DataTags
        >
      DataTags_var;

    typedef
      ::TAO_Out_T<
          DataTags
        >
      DataTags_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Dcps_Export DataTags
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DataTags_var _var_type;
      typedef DataTags_out _out_type;
      
      DDS::Security::TagSeq tags;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::ULong ParticipantSecurityAttributesMask;
    typedef ::CORBA::ULong_out ParticipantSecurityAttributesMask_out;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_PROTECTED = 1U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_PROTECTED = 2U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_PROTECTED = 4U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 2147483648U;

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::ULong PluginParticipantSecurityAttributesMask;
    typedef ::CORBA::ULong_out PluginParticipantSecurityAttributesMask_out;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_ENCRYPTED = 1U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_BUILTIN_IS_DISCOVERY_ENCRYPTED = 2U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_ENCRYPTED = 4U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_ORIGIN_AUTHENTICATED = 8U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_ORIGIN_AUTHENTICATED = 16U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_ORIGIN_AUTHENTICATED = 32U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 2147483648U;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct ParticipantSecurityInfo;

    typedef
      ::TAO_Fixed_Var_T<
          ParticipantSecurityInfo
        >
      ParticipantSecurityInfo_var;

    typedef
      ParticipantSecurityInfo &
      ParticipantSecurityInfo_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Dcps_Export ParticipantSecurityInfo
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef ParticipantSecurityInfo_var _var_type;
      typedef ParticipantSecurityInfo_out _out_type;
      
      DDS::Security::ParticipantSecurityAttributesMask participant_security_attributes;
      DDS::Security::PluginParticipantSecurityAttributesMask plugin_participant_security_attributes;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::ULong EndpointSecurityAttributesMask;
    typedef ::CORBA::ULong_out EndpointSecurityAttributesMask_out;

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::ULong PluginEndpointSecurityAttributesMask;
    typedef ::CORBA::ULong_out PluginEndpointSecurityAttributesMask_out;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_READ_PROTECTED = 1U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_WRITE_PROTECTED = 2U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_PROTECTED = 4U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_PROTECTED = 8U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_PAYLOAD_PROTECTED = 16U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_KEY_PROTECTED = 32U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_PROTECTED = 64U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 2147483648U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_ENCRYPTED = 1U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_PAYLOAD_ENCRYPTED = 2U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_ORIGIN_AUTHENTICATED = 4U;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct EndpointSecurityInfo;

    typedef
      ::TAO_Fixed_Var_T<
          EndpointSecurityInfo
        >
      EndpointSecurityInfo_var;

    typedef
      EndpointSecurityInfo &
      EndpointSecurityInfo_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Dcps_Export EndpointSecurityInfo
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef EndpointSecurityInfo_var _var_type;
      typedef EndpointSecurityInfo_out _out_type;
      
      DDS::Security::EndpointSecurityAttributesMask endpoint_security_attributes;
      DDS::Security::PluginEndpointSecurityAttributesMask plugin_endpoint_security_attributes;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:373

    typedef ::CORBA::ULong BuiltinEndpointSet_t;
    typedef ::CORBA::ULong_out BuiltinEndpointSet_t_out;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SEDP_BUILTIN_PUBLICATIONS_SECURE_WRITER = 65536U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SEDP_BUILTIN_PUBLICATIONS_SECURE_READER = 131072U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_WRITER = 262144U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_READER = 524288U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_MESSAGE_SECURE_WRITER = 1048576U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_MESSAGE_SECURE_READER = 2097152U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_STATELESS_MESSAGE_WRITER = 4194304U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_STATELESS_MESSAGE_READER = 8388608U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_WRITER = 16777216U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_READER = 33554432U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SPDP_BUILTIN_PARTICIPANT_SECURE_WRITER = 67108864U;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    const CORBA::ULong SPDP_BUILTIN_PARTICIPANT_SECURE_READER = 134217728U;
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:67
  
  } // module DDS::Security

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::DDS::Security::DataHolder>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::Security::DataHolder,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::DDS::Security::DataHolderSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::Security::DataHolderSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::DDS::Security::Tag>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::Security::Tag,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::DDS::Security::TagSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::Security::TagSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::DDS::Security::DataTags>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::Security::DataTags,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::DDS::Security::ParticipantSecurityInfo>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::Security::ParticipantSecurityInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::DDS::Security::EndpointSecurityInfo>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::Security::EndpointSecurityInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62


OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Security::DataHolder &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Security::DataHolder &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_DDS_Security_DataHolderSeq_H_
#define _TAO_CDR_OP_DDS_Security_DataHolderSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::Security::DataHolderSeq &_tao_sequence);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::Security::DataHolderSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_DDS_Security_DataHolderSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Security::Tag &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Security::Tag &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_DDS_Security_TagSeq_H_
#define _TAO_CDR_OP_DDS_Security_TagSeq_H_

OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDS::Security::TagSeq &_tao_sequence);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDS::Security::TagSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




#endif /* _TAO_CDR_OP_DDS_Security_TagSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Security::DataTags &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Security::DataTags &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Security::ParticipantSecurityInfo &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Security::ParticipantSecurityInfo &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Dcps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Security::EndpointSecurityInfo &);
OpenDDS_Dcps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Security::EndpointSecurityInfo &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_codegen.cpp:1703


OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "DdsSecurityParamsC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

